# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\tbookstore\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\tOrderInfo\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\xdd\x01\n\x1fTransactionVerificationResponse\x12\x17\n\x0fverification_id\x18\x01 \x01(\t\x12\x13\n\x0bis_verified\x18\x02 \x01(\x08\x12-\n\x06status\x18\x03 \x01(\x0e\x32\x1d.bookstore.VerificationStatus\x12/\n\x0bverified_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10rejection_reason\x18\x05 \x01(\t\x12\x12\n\nrisk_score\x18\x06 \x01(\x01*}\n\x12VerificationStatus\x12#\n\x1fVERIFICATION_STATUS_UNSPECIFIED\x10\x00\x12 \n\x1cVERIFICATION_STATUS_APPROVED\x10\x01\x12 \n\x1cVERIFICATION_STATUS_REJECTED\x10\x02\x32w\n\x1eTransactionVerificationService\x12U\n\x11VerifyTransaction\x12\x14.bookstore.OrderInfo\x1a*.bookstore.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFICATIONSTATUS']._serialized_start=379
  _globals['_VERIFICATIONSTATUS']._serialized_end=504
  _globals['_ORDERINFO']._serialized_start=107
  _globals['_ORDERINFO']._serialized_end=153
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=156
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=377
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=506
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=625
# @@protoc_insertion_point(module_scope)
