# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\tbookstore\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\tOrderInfo\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"V\n\x16\x46raudDetectionResponse\x12\x15\n\ris_fraudulent\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x11\n\treview_id\x18\x04 \x01(\t2\xb5\x01\n\x15\x46raudDetectionService\x12J\n\x0f\x44\x65tectUserFraud\x12\x14.bookstore.OrderInfo\x1a!.bookstore.FraudDetectionResponse\x12P\n\x15\x44\x65tectCreditCardFraud\x12\x14.bookstore.OrderInfo\x1a!.bookstore.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERINFO']._serialized_start=98
  _globals['_ORDERINFO']._serialized_end=144
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=146
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=232
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=235
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
